name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the code onto the GitHub runner
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Node and run tests (The CI part)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Tests
        run: npm test

      # Step 3: Authenticate with Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Bharath }}
          password: ${{ secrets.1234 }}

      # Step 4: Set up Docker's build engine
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Build the image and push it to Docker Hub (The CD part)
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tags the image with your Docker Hub username and app name
          tags: ${{ secrets.DOCKER_USERNAME }}/sample-node-app:latest